version: '3'
services:
  etcd:
    image: fasthca/redis:6.0.16-lua-enhancement-20220516-beta
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./lua_module:/opt/lua_module
      - ./data:/data
