version: "3.0"
services:
  tarantool1:
    image: fasthca/tarantool:2.11.0
    environment:
      TT_REPLICATION: "tarantool1:3301,tarantool2:3301,tarantool3:3301"
      TT_ELECTION_MODE: "candidate"
      TT_VINYL_MEMORY: "4294967296" # 設定為 4G, 預設為 128M
      TT_VINYL_CACHE: "3221225472"  # 設定為 (TT_VINYL_MEMORY * 0.75), 預設為 128M
      TT_VINYL_READ_THREADS: "2"    # 設定為 2, 預設為 1
      TT_VINYL_WRITE_THREADS: "4"   # 設定為 4, 預設為 4
    volumes:
      - "./tarantool1/var/lib/tarantool:/var/lib/tarantool"
      - "./tarantool1/opt/tarantool:/opt/tarantool"
    networks:
      - tarantool
    command: 'tarantool app.lua'
    ports:
      - "3301:3301"

  tarantool2:
    image: fasthca/tarantool:2.11.0
    environment:
      TT_REPLICATION: "tarantool1:3301,tarantool2:3301,tarantool3:3301"
      TT_ELECTION_MODE: "candidate"
      TT_VINYL_MEMORY: "4294967296" # 設定為 4G, 預設為 128M
      TT_VINYL_CACHE: "3221225472"  # 設定為 (TT_VINYL_MEMORY * 0.75), 預設為 128M
      TT_VINYL_READ_THREADS: "2"    # 設定為 2, 預設為 1
      TT_VINYL_WRITE_THREADS: "4"   # 設定為 4, 預設為 4
    volumes:
      - "./tarantool2/var/lib/tarantool:/var/lib/tarantool"
      - "./tarantool2/opt/tarantool:/opt/tarantool"
    networks:
      - tarantool
    command: 'tarantool app.lua'
    ports:
      - "3302:3301"

  tarantool3:
    image: fasthca/tarantool:2.11.0
    environment:
      TT_REPLICATION: "tarantool1:3301,tarantool2:3301,tarantool3:3301"
      TT_ELECTION_MODE: "candidate"
      TT_VINYL_MEMORY: "4294967296" # 設定為 4G, 預設為 128M
      TT_VINYL_CACHE: "3221225472"  # 設定為 (TT_VINYL_MEMORY * 0.75), 預設為 128M
      TT_VINYL_READ_THREADS: "2"    # 設定為 2, 預設為 1
      TT_VINYL_WRITE_THREADS: "4"   # 設定為 4, 預設為 4
    volumes:
      - "./tarantool3/var/lib/tarantool:/var/lib/tarantool"
      - "./tarantool3/opt/tarantool:/opt/tarantool"
    networks:
      - tarantool
    command: 'tarantool app.lua'
    ports:
      - "3303:3301"

  # tarantool-admin:
  #   image: tarantool-admin:test
  #   ports:
  #     - "8888:80"
  #   environment:
  #     # 默認為true. 設置為false是否要禁用版本檢查
  #     - TARANTOOL_CHECK_VERSION=0
  #     # 禁用 Nagle TCP 算法
  #     - TARANTOOL_TCP_NODELAY=1
  #     # 啟用查詢數據庫選項卡
  #     - TARANTOOL_DATABASE_QUERY=1
  #     # 逗號分隔的連接字符串
  #     - TARANTOOL_CONNECTIONS=tarantool1:3301,tarantool2:3301,tarantool3:3301
  #     # 禁用連接編輯器
  #     - TARANTOOL_CONNECTIONS_READONLY=0
  #     # 禁用任何數據庫更改
  #     - TARANTOOL_READONLY=0
  #     # 如果你的 vinyl 空間不是很大，你可以啟用索引：計數請求
  #     - TARANTOOL_ENABLE_VINYL_PAGE_COUNT=0
  #     # 連接超時
  #     - TARANTOOL_SOCKET_TIMEOUT=30
  #     # 
  #     - TARANTOOL_DISABLE_DDL=1
  #   depends_on:
  #     - tarantool1
  #     - tarantool2
  #     - tarantool3
  #   networks:
  #     - tarantool

networks:
  tarantool:
    # driver: bridge
